### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by NeserCode** [moeshin/QPlayer2-Typecho#1]
**播放器很好，赞👍**

但是，出现在这里，是有些话要说的。
在使用这款音乐播放器之前曾经用过Vue-APlayer构建我自己的网站，但由于目前用的当前网站用的是typecho建站，网上一番查找，找到这款播放器，感谢之余，提出：

    这个播放器为什么没有断点续播的功能呢，不知是我设置的问题还是插件没有相关功能。每次跳转都会刷新插件，从零开始，当然，也没有自动播放的功能。感觉用户体验会有些问题。

**Comment by moeshin** [comment]
我是配合 PJAX 使用哦，而且现在浏览器都禁止自动播放，就没有考虑这个断点续播哦。

不知道是否在找这个：[APlayer-Typecho](https://github.com/MoePlayer/APlayer-Typecho)
