### ISSUE TITLE
自动播放？

### ISSUE THREAD

**Issue by Dar1in9s** [moeshin/QPlayer2-Typecho#2]
请问可以设置自动播放吗？
如果可以，怎么设置呢？

**Comment by moeshin** [comment]
目前的浏览器基本默认不支持自动播放，需要在用户交互（点击、按键）之后才能播放。

https://goo.gl/xX8pDD

对此我只做了简单的监听，不是完美的解决方案。

### FireFox

可以手动设置每个网站的播放权限

### Chrome

> * On desktop, the user's Media Engagement Index threshold has been crossed, meaning the user has previously played video with sound.
> * The user has added the site to their home screen on mobile or installed the PWA on desktop.

* 电脑端，通过提高网站的 MEI 媒体参与指数，（chrome://media-engagement/ 下面列表网站的 Is High 为 Yes 时）即可自动播放。
* 手机端，通过将网站添加到手机主屏幕？没试成功

或者就是改启动项

> * You can disable entirely the autoplay policy by using an internal switch with `chrome.exe --autoplay-policy=no-user-gesture-required`. This allows you to test your website as if user were strongly engaged with your site and playback autoplay would be always allowed.
> * You can also decide to make sure playback autoplay is never allowed by disabling use of MEI, applying autoplay policy to Web Audio, and whether sites with the highest overall MEI get playback autoplay by default for new users. This can be done with three internal switches with `chrome.exe --disable-features=PreloadMediaEngagementData, MediaEngagementBypassAutoplayPolicies`.
