### ISSUE TITLE
悬浮播放器没有加载

### ISSUE THREAD

**Issue by CmmmmmmLau** [moeshin/QPlayer2-Typecho#3]
看了下疑似跟主题冲突了,切换到默认主题就可以在左下角看到播放器了
PHP 7.3 + SQLite3
主题是icarus
https://github.com/keroliang/typecho-theme-icarus

**Comment by moeshin** [comment]
好像是这个主题没有实现插件。

简单一点就在 `component/footer.php` 最后的 `</body>` 前加上 `$this->footer();`

https://github.com/keroliang/typecho-theme-icarus/blob/d648631f58daa28033e2e358abc8d95ea28caf5b/component/footer.php#L55-L67

```php
<?php
Icarus_Module::show('Search');

Icarus_Assets::cdn('js', 'jquery', '3.3.1', 'jquery.min.js');

Icarus_Plugin::footerAll();

Icarus_Assets::printThemeJs('main.js', TRUE);

echo Icarus_Config::get('footer_scripts');

$this->footer(); // 加了这一行
?>
</body>
</html>
```

**Comment by CmmmmmmLau** [comment]
> 

解决了,但是回头又发现这个主题不支持Pjax播放器会被刷新掉. 还不方便自己加进去.
