### ISSUE TITLE
能否新增一个功能

### ISSUE THREAD

**Issue by DumbBearW** [moeshin/QPlayer2-Typecho#4]
就是指定日期不加载和播放音乐，比如今天这种公祭日。
刚刚在查找黑白插件时找到一个可以指定日期黑白的，所以顺便来问问

**Comment by moeshin** [comment]
这个可以自己写个 js 实现吧
隐藏 `QPlayer.$('#QPlayer').hide()`
颜色 `QPlayer.setColor('#000000')` 或者自己改样式吧
